[package]
name = "kaspa-wallet-recovery"
version = "0.1.0"
edition = "2021"

[dependencies]
# kaspa-wallet-core = "*"
kaspa-wallet-keys = "*"
kaspa-bip32 = "*"
kaspa-utils = "*"
kaspa-addresses = "*"
workflow-core = "*"
hmac="*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"